# Pagination
paginate: 3
pagination: true


# Site info
name: Belgian Police Internet Platform
# url: http://localhost:4000


# Navigation
navigation:
- text: Blog
  url: blog
- text: Styleguide
  url: styleguide


# Code highlighting
highlighter: pygments


sass:
    sass_dir: _sass
    style: :compressed


# Blog separator
# excerpt_separator: <!--more-->

# We don't want to publish some files
exclude: ['Gemfile', 'Gemfile.lock', 'Rakefile', 'README.md']