# Pagination
paginate: 3
paginate_path: "blog/page:num"
paginate_limit: 5

# Site info
name: Open Police
url: http://www.openpolice.be

# Collections
collections:
  documentation:
    output: true
  about:
    output: true
  guides:
    output: true

# Code highlighting
highlighter: pygments

# Gems
gems:
  - jekyll-sitemap
  - jekyll-category-aware-prev-next

# We don't want to publish some files
exclude: [
  'Gemfile',
  'Gemfile.lock',
  'Rakefile',
  'README.md',
  'node_modules',
  'vendor',
  'bower.json',
  'package.json',
  'gruntfile.js',
  'CONTRIBUTING.md'
  ]

# Static information
blog_description: A product blog about developing and iterating the Belgian Police Web Platform. For the people who publish content to their site and anyone else who is interested.

# Compress HTML - https://github.com/penibelst/jekyll-compress-html
compress_html:
  comments: ["<!-- ", " -->"]