# Pagination
paginate: 3
pagination: true
paginate_path: "blog/page:num"

gems:
- jekyll-mentions
- jemoji
- jekyll-redirect-from
- jekyll-sitemap


# Site info
name: Belgian Police Internet Platform - Blog
# url: http://localhost:4000


# Navigation
navigation:
- text: Styleguide
  url: styleguide
- text: Blog
  url: blog


# Code highlighting
highlighter: pygments

# Markdown interpreter
markdown: kramdown


# Blog separator
# excerpt_separator: <!--more-->