# Pagination
paginate: 3
pagination: true


# Site info
name: Belgian Police Internet Platform - Blog
# url: http://localhost:4000


# Code highlighting
highlighter: pygments


# Blog separator
# excerpt_separator: <!--more-->